import React from "react";
import { useState } from "react";
import { NextPage } from 'next'
import Head from "next/head";
import Footer from "../components/layouts/Footer";
import Header from "../components/layouts/Header";
import Navbar from "../components/layouts/Navbar";

const Home: NextPage = () => {
  const [openNav, setOpenNav] = useState(false)

  const openNavHandler = () => {
    setOpenNav(!openNav);
  }
  return (
    <div className="relative min-h-screen bg-neutral-1000">
      <Head>
        <title>Trading Journal</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Header openNav={openNavHandler}/>
      <Navbar active={openNav}/>
      <div className="overflow-hidden">
        <div className="mx-4 mt-20 mb-12 md:ml-20 md:mr-4">
          <p>TEST TEXT YAY!!!312313!</p>
          <p>TEST TEXT YAY!!!!</p>
          <p>TEST TEXT YAY!!!!</p>
          <p>TEST TEXT YAY!!!!</p>
  
          <p>TEST TEXT YAY!!!!</p>
          <p>TEST TEXT YAY!!!!</p>
          <p>TEST TEXT YAY!!!!</p>
          <p>TEST TEXT YAY!!!!</p>
          <p>TEST TEXT YAY!!!!</p>
          <p>TEST TEXT YAY!!!!</p>
          <p>TEST TEXT YAY!2131231!!!</p>
        </div>
      </div>
      <Footer />
    </div>
  )
}

export default Home
